definitions:
  api.AuthenticateConfig:
    properties:
      google_code:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: luyu151111@gmail.com
    name: SmartLyu go-core Support
    url: https://github.com/SmartLyu/go-core/blob/main/README.md
  description: SmartLyu go-core API
  title: Swagger SmartLyu go-core API
  version: 1.0.0
paths:
  /authenticate:
    post:
      consumes:
      - application/json
      description: 登录认证
      parameters:
      - description: Account Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/api.AuthenticateConfig'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "401":
          description: 未授权
          schema:
            type: string
        "407":
          description: 权限不足
          schema:
            type: string
        "501":
          description: 处理存在异常
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 登录认证
      tags:
      - login
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
